{
    "_id" : 4,
    "idx" : "TBD4",
    "name" : "Efficiency, Productivity & Service Quality ",
    "description" : "Improve efficiency, productivity and service quality",
    "updatedby" : "",
    "updateddate" : ISODate("2019-02-25T10:10:01.375Z"),
    "businessmetric" : [ 
        {
            "id" : "BM274",
            "DataPoint" : "18. Productivity Index",
            "DecimalFormat" : "1",
            "MetricType" : "PERCENTAGE",
            "bdid" : "",
            "description" : "18. Productivity Index",
            "valuetype" : 1,
            "metricdirection" : 0,
            "type" : "spot",
            "targetperiod" : Date(-62135596800000),
            "targetperiodstr" : "2019-03-01T08:00:00+08:00",
            "targetvalue" : 0.0,
            "baselineperiod" : ISODate("2019-01-01T03:28:11.314Z"),
            "baselineperiodstr" : "2019-01-01T11:28:11.314+08:00",
            "baselinevalue" : 0.0,
            "currentperiod" : Date(-62135596800000),
            "currentperiodstr" : "0001-01-01T00:00:00Z",
            "currentvalue" : 0.0,
            "currentytdvalue" : 0.0,
            "currentytdvaluevsbudget" : 0.0,
            "totargetytd" : 0.0,
            "display" : "",
            "chainid" : "",
            "chainname" : "Select..",
            "chainyear" : 2018,
            "nabaseline" : true,
            "naactual" : true,
            "natarget" : true,
            "nabudget" : true,
            "natotargetytd" : true,
            "regionaldata" : [ 
                {
                    "name" : "GCNA",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }, 
                {
                    "name" : "ASA",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }, 
                {
                    "name" : "AME",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }
            ],
            "countrydata" : [],
            "actualdata" : [],
            "MetricFiles" : [],
            "orderindex" : 0,
            "previousvalue" : 0.0,
            "updateddate" : Date(-62135596800000),
            "baselinevaluestr" : "",
            "targetvaluestr" : "",
            "currentytdvaluestr" : "",
            "currentvaluestr" : ""
        }, 
        {
            "id" : "BM275",
            "DataPoint" : "19. Execute on organizational design and strategic headcount initiatives",
            "DecimalFormat" : "0",
            "MetricType" : "PERCENTAGE",
            "bdid" : "",
            "description" : "19. Execute on organizational design and strategic headcount i",
            "valuetype" : 1,
            "metricdirection" : 0,
            "type" : "spot",
            "targetperiod" : Date(-62135596800000),
            "targetperiodstr" : "2019-03-01T08:00:00+08:00",
            "targetvalue" : 0.0,
            "baselineperiod" : ISODate("2019-01-01T03:28:11.000Z"),
            "baselineperiodstr" : "2019-01-01T11:28:11+08:00",
            "baselinevalue" : 0.0,
            "currentperiod" : Date(-62135596800000),
            "currentperiodstr" : "0001-01-01T00:00:00Z",
            "currentvalue" : 0.0,
            "currentytdvalue" : 0.0,
            "currentytdvaluevsbudget" : 0.0,
            "totargetytd" : 0.0,
            "display" : "",
            "chainid" : "",
            "chainname" : "Select..",
            "chainyear" : 2018,
            "nabaseline" : true,
            "naactual" : true,
            "natarget" : true,
            "nabudget" : true,
            "natotargetytd" : true,
            "regionaldata" : [ 
                {
                    "name" : "GCNA",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }, 
                {
                    "name" : "ASA",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }, 
                {
                    "name" : "AME",
                    "baseline" : 0.0,
                    "currentytdvalue" : 0.0,
                    "currentytdvaluevsbudget" : 0.0,
                    "totargetytd" : 0.0,
                    "target" : 0.0,
                    "nabaseline" : true,
                    "naactual" : true,
                    "nabudget" : true,
                    "natarget" : true,
                    "natotargetytd" : true,
                    "rag" : "",
                    "baselinestr" : "",
                    "targetstr" : "",
                    "currentytdvaluestr" : "",
                    "currentvaluestr" : ""
                }
            ],
            "countrydata" : [],
            "actualdata" : [ 
                {
                    "period" : Date(-62135596800000),
                    "periodstr" : "2018-11-01T08:00:00+08:00",
                    "value" : 0.0,
                    "flag" : "A1"
                }, 
                {
                    "period" : Date(-62135596800000),
                    "periodstr" : "2018-12-01T08:00:00+08:00",
                    "value" : 0.0,
                    "flag" : "A2"
                }, 
                {
                    "period" : Date(-62135596800000),
                    "periodstr" : "2019-01-01T08:00:00+08:00",
                    "value" : 0.0,
                    "flag" : "A3"
                }, 
                {
                    "period" : Date(-62135596800000),
                    "periodstr" : "2019-02-01T08:00:00+08:00",
                    "value" : 0.0,
                    "flag" : "C1"
                }
            ],
            "MetricFiles" : [],
            "orderindex" : 0,
            "previousvalue" : 0.0,
            "updateddate" : Date(-62135596800000),
            "baselinevaluestr" : "",
            "targetvaluestr" : "",
            "currentytdvaluestr" : "",
            "currentvaluestr" : ""
        }
    ],
    "seq" : 4
}
